# Generated by Django 5.0.6 on 2024-07-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgId',
        ),
    ]
